
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jnda
 */
public class ClienteAreaVolumen extends javax.swing.JFrame {

    /**
     * Creates new form VolumenAreaCliente
     */
    public RemotaVolumenArea vya;

    public ClienteAreaVolumen() {
        initComponents();
        try {
            vya = (RemotaVolumenArea) Naming.lookup("rmi://localhost/VolumenesYareasServer");
            System.out.println("Constructor client!!");
        } catch (MalformedURLException | RemoteException | NotBoundException m) {
            System.out.println(m.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEsfera = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcularEsfera = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtRadioEsfera = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoEsfera = new javax.swing.JTextArea();
        panelCilindro = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCalcularCilindro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRadioCilindro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAlturaCilindro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoCilindro = new javax.swing.JTextArea();
        panelCono = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCalcularCono = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtRadioCono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAlturaCono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtgeneratrizCono = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultadoCono = new javax.swing.JTextArea();
        panelCubo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnCalcularCubo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtLadoCubo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResultadoCubo = new javax.swing.JTextArea();
        panelOrtoedro = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResultadoOrtoedro = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnOrtoedro = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtAltoOrtoedro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAnchoOrtoedro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtProfundoOrtoedro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelEsfera.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("CONTROLES");

        btnCalcularEsfera.setText("Calcular");
        btnCalcularEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEsferaActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese el radio:");

        txtRadioEsfera.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnCalcularEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(txtRadioEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRadioEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCalcularEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        txtResultadoEsfera.setColumns(20);
        txtResultadoEsfera.setRows(5);
        jScrollPane1.setViewportView(txtResultadoEsfera);

        javax.swing.GroupLayout panelEsferaLayout = new javax.swing.GroupLayout(panelEsfera);
        panelEsfera.setLayout(panelEsferaLayout);
        panelEsferaLayout.setHorizontalGroup(
            panelEsferaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsferaLayout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelEsferaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEsferaLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(405, Short.MAX_VALUE)))
        );
        panelEsferaLayout.setVerticalGroup(
            panelEsferaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsferaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(panelEsferaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEsferaLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Esfera", panelEsfera);

        panelCilindro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("CONTROLES");

        btnCalcularCilindro.setText("Calcular");
        btnCalcularCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCilindroActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrese el radio:");

        txtRadioCilindro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Ingrese la altura:");

        txtAlturaCilindro.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnCalcularCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlturaCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRadioCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtRadioCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlturaCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnCalcularCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        txtResultadoCilindro.setColumns(20);
        txtResultadoCilindro.setRows(5);
        jScrollPane2.setViewportView(txtResultadoCilindro);

        javax.swing.GroupLayout panelCilindroLayout = new javax.swing.GroupLayout(panelCilindro);
        panelCilindro.setLayout(panelCilindroLayout);
        panelCilindroLayout.setHorizontalGroup(
            panelCilindroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCilindroLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelCilindroLayout.setVerticalGroup(
            panelCilindroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCilindroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCilindroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cilindro", panelCilindro);

        panelCono.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("CONTROLES");

        btnCalcularCono.setText("Calcular");
        btnCalcularCono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularConoActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese el radio:");

        txtRadioCono.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Ingrese la altura:");

        txtAlturaCono.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Ingrese la generatriz:");

        txtgeneratrizCono.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlturaCono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRadioCono, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgeneratrizCono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnCalcularCono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadioCono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlturaCono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgeneratrizCono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularCono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtResultadoCono.setColumns(20);
        txtResultadoCono.setRows(5);
        jScrollPane3.setViewportView(txtResultadoCono);

        javax.swing.GroupLayout panelConoLayout = new javax.swing.GroupLayout(panelCono);
        panelCono.setLayout(panelConoLayout);
        panelConoLayout.setHorizontalGroup(
            panelConoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelConoLayout.setVerticalGroup(
            panelConoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cono", panelCono);

        panelCubo.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("CONTROLES");

        btnCalcularCubo.setText("Calcular");
        btnCalcularCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCuboActionPerformed(evt);
            }
        });

        jLabel12.setText("Ingrese el lado:");

        txtLadoCubo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnCalcularCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(txtLadoCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtLadoCubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCalcularCubo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        txtResultadoCubo.setColumns(20);
        txtResultadoCubo.setRows(5);
        jScrollPane4.setViewportView(txtResultadoCubo);

        javax.swing.GroupLayout panelCuboLayout = new javax.swing.GroupLayout(panelCubo);
        panelCubo.setLayout(panelCuboLayout);
        panelCuboLayout.setHorizontalGroup(
            panelCuboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuboLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        panelCuboLayout.setVerticalGroup(
            panelCuboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuboLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelCuboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Cubo", panelCubo);

        panelOrtoedro.setBackground(new java.awt.Color(255, 255, 255));

        txtResultadoOrtoedro.setColumns(20);
        txtResultadoOrtoedro.setRows(5);
        jScrollPane5.setViewportView(txtResultadoOrtoedro);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("CONTROLES");

        btnOrtoedro.setText("Calcular");
        btnOrtoedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrtoedroActionPerformed(evt);
            }
        });

        jLabel14.setText("Ingrese el alto:");

        txtAltoOrtoedro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Ingrese la ancho:");

        txtAnchoOrtoedro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Ingrese la profundo:");

        txtProfundoOrtoedro.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnchoOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltoOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfundoOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltoOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnchoOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfundoOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrtoedro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelOrtoedroLayout = new javax.swing.GroupLayout(panelOrtoedro);
        panelOrtoedro.setLayout(panelOrtoedroLayout);
        panelOrtoedroLayout.setHorizontalGroup(
            panelOrtoedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrtoedroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelOrtoedroLayout.setVerticalGroup(
            panelOrtoedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrtoedroLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelOrtoedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Ortoedro", panelOrtoedro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEsferaActionPerformed
       txtResultadoEsfera.setText("");
        if (!(txtRadioEsfera.getText().equals(""))) {
            
            double radio = Double.parseDouble(txtRadioEsfera.getText());
            double resultadoArea = 0;
            double resultadoVolumen = 0;
            String resultado = "";
            
            try {
                resultadoArea = vya.calcularAEsfera(radio);
                resultadoVolumen = vya.calcularVEsfera(radio);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            resultado += "El área de la esfera es ==> " + resultadoArea + "\n" +
                    "El Volumen de la esfera es ==> " + resultadoVolumen + "\n";
            txtResultadoEsfera.setText(resultado);
        } else {
            JOptionPane.showMessageDialog(this, "Error ingresando datos", "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularEsferaActionPerformed

    private void btnCalcularCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCilindroActionPerformed
         txtResultadoCilindro.setText("");
        if (!(txtRadioCilindro.getText().equals(""))
                && !(txtAlturaCilindro.getText().equals(""))) {
            
            double radio = Double.parseDouble(txtRadioCilindro.getText());
            double altura = Double.parseDouble(txtAlturaCilindro.getText());
            double resultadoArea = 0;
            double resultadoVolumen = 0;
            String resultado = "";
            
            try {
                resultadoArea = vya.calcularACilindro(radio, altura);
                resultadoVolumen = vya.calcularVCilindro(radio, altura);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            resultado += "El área del cilindro es ==> " + resultadoArea + "\n" +
                    "El Volumen del cilindro es ==> " + resultadoVolumen + "\n";
            txtResultadoCilindro.setText(resultado);
        } else {
            JOptionPane.showMessageDialog(this, "Error ingresando datos", "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularCilindroActionPerformed

    private void btnCalcularConoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularConoActionPerformed
         txtResultadoCono.setText("");
        if (!(txtRadioCono.getText().equals(""))
                && !(txtAlturaCono.getText().equals(""))
                && !(txtgeneratrizCono.getText().equals(""))) {
            
            double radio = Double.parseDouble(txtRadioCono.getText());
            double altura = Double.parseDouble(txtAlturaCono.getText());
            double generatriz = Double.parseDouble(txtgeneratrizCono.getText());
            double resultadoArea = 0;       
            double resultadoVolumen = 0;
            String resultado = "";
            
            try {
                resultadoArea = vya.calcularACono(radio, generatriz);
                resultadoVolumen = vya.calcularVCono(radio, altura);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            resultado += "El área del cono es ==> " + resultadoArea + "\n" +
                    "El Volumen del cono es ==> " + resultadoVolumen + "\n";
            txtResultadoCono.setText(resultado);
        } else {
            JOptionPane.showMessageDialog(this, "Error ingresando datos", "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularConoActionPerformed

    private void btnCalcularCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCuboActionPerformed
         txtResultadoCubo.setText("");
        if (!(txtLadoCubo.getText().equals(""))) {
            
            double lado = Double.parseDouble(txtLadoCubo.getText());
            double resultadoArea = 0;
            double resultadoVolumen = 0;
            String resultado = "";
            
            try {
                resultadoArea = vya.calcularACubo(lado);
                resultadoVolumen = vya.calcularVCubo(lado);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            resultado += "El área del cubo es ==> " + resultadoArea + "\n" +
                    "El Volumen del cubo es ==> " + resultadoVolumen + "\n";
            txtResultadoCubo.setText(resultado);
        } else {
            JOptionPane.showMessageDialog(this, "Error ingresando datos", "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularCuboActionPerformed

    private void btnOrtoedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrtoedroActionPerformed
         txtResultadoOrtoedro.setText("");
        if (!(txtAltoOrtoedro.getText().equals(""))
                && !(txtAnchoOrtoedro.getText().equals("")) 
                && !(txtProfundoOrtoedro.getText().equals(""))) {
            
            double alto = Double.parseDouble(txtAltoOrtoedro.getText());
            double ancho = Double.parseDouble(txtAnchoOrtoedro.getText());
            double profundo = Double.parseDouble(txtProfundoOrtoedro.getText());
            double resultadoArea = 0;
            double resultadoVolumen = 0;
            String resultado = "";
            
            try {
                resultadoArea = vya.calcularAOrtoedro(alto, ancho, profundo);
                resultadoVolumen = vya.calcularVOrtoedro(alto, ancho, profundo);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            
            resultado += "El área del ortoedro es ==> " + resultadoArea + "\n" +
                    "El Volumen del ortoedro es ==> " + resultadoVolumen + "\n";
            txtResultadoOrtoedro.setText(resultado);
        } else {
            JOptionPane.showMessageDialog(this, "Error ingresando datos", "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOrtoedroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteAreaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteAreaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteAreaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteAreaVolumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteAreaVolumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularCilindro;
    private javax.swing.JButton btnCalcularCono;
    private javax.swing.JButton btnCalcularCubo;
    private javax.swing.JButton btnCalcularEsfera;
    private javax.swing.JButton btnOrtoedro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelCilindro;
    private javax.swing.JPanel panelCono;
    private javax.swing.JPanel panelCubo;
    private javax.swing.JPanel panelEsfera;
    private javax.swing.JPanel panelOrtoedro;
    private javax.swing.JTextField txtAltoOrtoedro;
    private javax.swing.JTextField txtAlturaCilindro;
    private javax.swing.JTextField txtAlturaCono;
    private javax.swing.JTextField txtAnchoOrtoedro;
    private javax.swing.JTextField txtLadoCubo;
    private javax.swing.JTextField txtProfundoOrtoedro;
    private javax.swing.JTextField txtRadioCilindro;
    private javax.swing.JTextField txtRadioCono;
    private javax.swing.JTextField txtRadioEsfera;
    private javax.swing.JTextArea txtResultadoCilindro;
    private javax.swing.JTextArea txtResultadoCono;
    private javax.swing.JTextArea txtResultadoCubo;
    private javax.swing.JTextArea txtResultadoEsfera;
    private javax.swing.JTextArea txtResultadoOrtoedro;
    private javax.swing.JTextField txtgeneratrizCono;
    // End of variables declaration//GEN-END:variables
}
